import {
  STYLE_KIT_CONTRACT_VERSION,
  validateStyleKitContract,
} from "../style-kit-contracts";

const RIG_ID = "humanoid-basic-v1";
const rigCompatible = [RIG_ID] as const;

export const humanoidChibiStyleKitV1 = validateStyleKitContract({
  contractVersion: STYLE_KIT_CONTRACT_VERSION,
  id: "humanoid/chibi-style-kit",
  version: "1.0.0",
  modelTypeId: "humanoid/chibi-v1",
  rigId: RIG_ID,
  slots: [
    {
      id: "body-shape",
      label: "Body Shape",
      required: true,
      kind: "structural",
      parentPartId: null,
      anchorId: "root",
      deformationRole: "skinned",
      variants: [
        { id: "gold-standard", label: "Classic Chibi", sourceId: "chibi/body/gold-standard-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
    {
      id: "head-shape",
      label: "Head Shape",
      required: true,
      kind: "structural",
      parentPartId: "body",
      anchorId: "head",
      deformationRole: "skinned",
      variants: [
        { id: "soft-round", label: "Soft Round", sourceId: "chibi/head/soft-round-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
    {
      id: "eyes",
      label: "Eyes",
      required: true,
      kind: "presentation",
      parentPartId: "head",
      anchorId: "head",
      deformationRole: "presentation",
      variants: [
        { id: "vertical-oval", label: "Vertical Oval", sourceId: "chibi/eyes/vertical-oval-v1", compatibleRigIds: rigCompatible, materialSlots: ["eyes"] },
      ],
    },
    {
      id: "nose",
      label: "Nose",
      required: true,
      kind: "presentation",
      parentPartId: "head",
      anchorId: "head",
      deformationRole: "presentation",
      variants: [
        { id: "minimal", label: "Minimal", sourceId: "chibi/nose/minimal-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
    {
      id: "mouth",
      label: "Mouth",
      required: true,
      kind: "presentation",
      parentPartId: "head",
      anchorId: "head",
      deformationRole: "presentation",
      variants: [
        { id: "simple-line", label: "Simple Line", sourceId: "chibi/mouth/simple-line-v1", compatibleRigIds: rigCompatible, materialSlots: ["mouth"] },
      ],
    },
    {
      id: "ears",
      label: "Ears",
      required: true,
      kind: "presentation",
      parentPartId: "head",
      anchorId: "head",
      deformationRole: "presentation",
      variants: [
        { id: "rounded", label: "Rounded", sourceId: "chibi/ears/rounded-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
    {
      id: "hair",
      label: "Hair",
      required: true,
      kind: "presentation",
      parentPartId: "head",
      anchorId: "head",
      deformationRole: "presentation",
      variants: [
        { id: "faceted-cap", label: "Faceted Cap", sourceId: "chibi/hair/faceted-cap-v1", compatibleRigIds: rigCompatible, materialSlots: ["hair"] },
      ],
    },
    {
      id: "torso-clothing",
      label: "Torso Clothing",
      required: true,
      kind: "presentation",
      parentPartId: "body",
      anchorId: "chest",
      deformationRole: "skinned",
      variants: [
        { id: "a-frame-briefs", label: "A-frame + Briefs", sourceId: "chibi/clothing/a-frame-briefs-v1", compatibleRigIds: rigCompatible, materialSlots: ["shirt", "briefs"] },
      ],
    },
    {
      id: "hands",
      label: "Hands",
      required: true,
      kind: "structural",
      parentPartId: "body",
      anchorId: "hands",
      deformationRole: "skinned",
      variants: [
        { id: "oversized-simple", label: "Oversized Simple", sourceId: "chibi/hands/oversized-simple-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
    {
      id: "feet",
      label: "Feet",
      required: true,
      kind: "structural",
      parentPartId: "body",
      anchorId: "feet",
      deformationRole: "skinned",
      variants: [
        { id: "bare-oversized", label: "Bare Oversized", sourceId: "chibi/feet/bare-oversized-v1", compatibleRigIds: rigCompatible, materialSlots: ["skin"] },
      ],
    },
  ],
  controls: [
    { id: "heads-tall", label: "Head Size", implementationKey: "heads_tall", min: 2.6, max: 2.8, default: 2.7, affectedSlotIds: ["body-shape", "head-shape"], affectedAnchorIds: ["root", "head"] },
    { id: "head-width", label: "Head Width", implementationKey: "head_width_as_head_height", min: 0.88, max: 1.14, default: 1.02, affectedSlotIds: ["head-shape", "eyes", "ears", "hair"], affectedAnchorIds: ["head"] },
    { id: "head-depth", label: "Head Depth", implementationKey: "head_depth_as_head_height", min: 0.78, max: 1.1, default: 0.95, affectedSlotIds: ["head-shape", "ears", "hair"], affectedAnchorIds: ["head"] },
    { id: "eye-spacing", label: "Eye Spacing", implementationKey: "eye_spacing_ratio", min: 0.28, max: 0.52, default: 0.38, affectedSlotIds: ["eyes"], affectedAnchorIds: ["head"] },
    { id: "eye-height", label: "Eye Height", implementationKey: "eye_center_from_top_ratio", min: 0.24, max: 0.32, default: 0.28, affectedSlotIds: ["eyes"], affectedAnchorIds: ["head"] },
    { id: "shoulder-width", label: "Shoulder Width", implementationKey: "shoulder_width_ratio", min: 0.62, max: 0.82, default: 0.72, affectedSlotIds: ["body-shape", "torso-clothing"], affectedAnchorIds: ["shoulder.L", "shoulder.R"] },
    { id: "waist-width", label: "Waist Width", implementationKey: "waist_width_ratio", min: 0.42, max: 0.6, default: 0.5, affectedSlotIds: ["body-shape", "torso-clothing"], affectedAnchorIds: ["hips"] },
    { id: "arm-length", label: "Arm Length", implementationKey: "arm_length_ratio", min: 0.23, max: 0.31, default: 0.27, affectedSlotIds: ["body-shape", "hands"], affectedAnchorIds: ["shoulder.L", "shoulder.R", "hand.L", "hand.R"] },
    { id: "leg-width", label: "Leg Width", implementationKey: "thigh_width_ratio", min: 0.24, max: 0.32, default: 0.28, affectedSlotIds: ["body-shape", "feet"], affectedAnchorIds: ["thigh.L", "thigh.R", "foot.L", "foot.R"] },
    { id: "foot-length", label: "Foot Length", implementationKey: "foot_length_ratio", min: 0.25, max: 0.35, default: 0.3, affectedSlotIds: ["feet"], affectedAnchorIds: ["foot.L", "foot.R"] },
    { id: "cheek-fullness", label: "Cheek Fullness", implementationKey: "cheek_fullness", min: 0.95, max: 1.15, default: 1.08, affectedSlotIds: ["head-shape"], affectedAnchorIds: ["head"] },
    { id: "cranium-roundness", label: "Cranium Roundness", implementationKey: "cranium_roundness", min: 0.96, max: 1.12, default: 1.06, affectedSlotIds: ["head-shape", "hair"], affectedAnchorIds: ["head"] },
  ],
  presets: [
    {
      id: "gold-standard",
      label: "Gold Standard Chibi",
      selections: {
        "body-shape": "gold-standard",
        "head-shape": "soft-round",
        eyes: "vertical-oval",
        nose: "minimal",
        mouth: "simple-line",
        ears: "rounded",
        hair: "faceted-cap",
        "torso-clothing": "a-frame-briefs",
        hands: "oversized-simple",
        feet: "bare-oversized",
      },
      parameters: {
        "heads-tall": 2.7,
        "head-width": 1.02,
        "head-depth": 0.95,
        "eye-spacing": 0.38,
        "eye-height": 0.28,
        "shoulder-width": 0.72,
        "waist-width": 0.5,
        "arm-length": 0.27,
        "leg-width": 0.28,
        "foot-length": 0.3,
        "cheek-fullness": 1.08,
        "cranium-roundness": 1.06,
      },
    },
  ],
  defaultPresetId: "gold-standard",
});
